In [2]:
from pathlib import Path
# 源域路径
src_1 = Path("./雷达数据集/捕获模式/源域")
src_2 = Path("./雷达数据集/搜索模式/源域")
src_3 = Path("./雷达数据集/跟踪模式/源域")
# 目标域路径
src_files = list(src_1.iterdir())+ list(src_2.iterdir())+ list(src_3.iterdir())

dst_1 = Path("./雷达数据集/捕获模式/目标域")
dst_2 = Path("./雷达数据集/搜索模式/目标域")
dst_3 = Path("./雷达数据集/跟踪模式/目标域")

dst_files = list(dst_1.iterdir())+ list(dst_3.iterdir())+ list(dst_3.iterdir())

print(dst_files)
#print(files[0].absolute())


[PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式1(w8w8w8w8).csv'), PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式(w4w4w4w2).csv'), PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式(w3w3w3w1).csv'), PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式(w1w2w2w2).csv'), PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式(w2w1w1w1).csv'), PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式1(w6w6w6w6).csv'), PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式1(w5w5w5w5).csv'), PosixPath('雷达数据集/捕获模式/目标域/目标域捕获模式1(w7w7w7w7).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式1(w2w4w4w4).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式(w9w7w7w7).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式1(w1w3w3w3).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式(w1w6w6w6).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式1(w3w1w1w1).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式(w4w6w6w6).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式1(w2w4w4w4).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式(w9w7w7w7).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式1(w1w3w3w3).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式(w1w6w6w6).csv'), PosixPath('雷达数据集/跟踪模式/目标域/目标域跟踪模式1(w3w1w1w1).csv'), PosixPath('雷达数据集/跟踪模

In [3]:

origin_col = ['w2脉冲幅值', 'w2幅值_固定', 'w2幅值_跳变', 'w2幅值_滑变', 'w2幅值_组变', 'w2幅值_参差',
       'w2脉冲载频', 'w2载频_固定', 'w2载频_跳变', 'w2载频_滑变', 'w2载频_组变', 'w2载频_参差',
       'w2重复周期', 'w2周期_固定', 'w2周期_跳变', 'w2周期_滑变', 'w2周期_组变', 'w2周期_参差',
       'w2脉冲宽度', 'w2脉宽_固定', 'w2脉宽_跳变', 'w2脉宽_滑变', 'w2脉宽_组变', 'w2脉宽_参差']

new_col = [item for item in 'abcdefghijklmnopqrstuvwx']
col_mapper = dict(zip(origin_col,new_col))
col_mapper
#data.columns

{'w2脉冲幅值': 'a',
 'w2幅值_固定': 'b',
 'w2幅值_跳变': 'c',
 'w2幅值_滑变': 'd',
 'w2幅值_组变': 'e',
 'w2幅值_参差': 'f',
 'w2脉冲载频': 'g',
 'w2载频_固定': 'h',
 'w2载频_跳变': 'i',
 'w2载频_滑变': 'j',
 'w2载频_组变': 'k',
 'w2载频_参差': 'l',
 'w2重复周期': 'm',
 'w2周期_固定': 'n',
 'w2周期_跳变': 'o',
 'w2周期_滑变': 'p',
 'w2周期_组变': 'q',
 'w2周期_参差': 'r',
 'w2脉冲宽度': 's',
 'w2脉宽_固定': 't',
 'w2脉宽_跳变': 'u',
 'w2脉宽_滑变': 'v',
 'w2脉宽_组变': 'w',
 'w2脉宽_参差': 'x'}

In [58]:
import pandas as pd

new_col = [item for item in 'abcdefghijklmnopqrstuvwx']
col_mapper = dict(zip(origin_col,new_col))
new_col.append('label')


['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'label']
(1240, 25)


a    b    c    d    e    f    g    h    i    j  ...    p    q    r  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1235  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1236  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1237  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1238  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1239  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        s    t    u    v    w    x  label  
0     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
1     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
2     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
3     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
4     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
...   ...  ...  ...  ...  ...  ...    ...  
1235  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
1236  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
1237  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
1238  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
1239  0.0  0.0  0.0  0.0  0.0  0.0    2.0  

[1240 rows x 25 columns]

In [74]:
import pandas as pd
from tqdm import tqdm

# merge data
source_pd_data = pd.read_csv(src_files[0].absolute(),encoding='gbk',dtype='float32')
source_pd_data.columns = new_col
for file in tqdm(src_files[1:]):
    # 忽略第一行
    d = pd.read_csv(file.absolute(),encoding='gbk',dtype='float32')
    d.columns = new_col
    source_pd_data = pd.concat([source_pd_data,d])
    
print(source_pd_data.isnull().sum())
source_pd_data.to_csv("./source_data.csv",index=False)
source_pd_data.head(30)
    


100%|██████████| 25/25 [00:00<00:00, 200.89it/s]


a        0
b        0
c        0
d        0
e        0
f        0
g        0
h        0
i        0
j        0
k        0
l        0
m        0
n        0
o        0
p        0
q        0
r        0
s        0
t        0
u        0
v        0
w        0
x        0
label    0
dtype: int64


a    b          c    d    e    f       g    h    i    j  ...  \
0    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
1    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
2    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
3    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
4    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
5    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
6    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
7    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
8    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
9    0.000000  0.0   0.000000  0.0  0.0  0.0     0.0  0.0  0.0  0.0  ...   
10  18.033628  0.0  18.033628  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
11  22.515211  0.0  22.515211  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
12  24.135885  0.0  24.135885  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
13  19.510384  0.0  19.510384  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
14  17.940912  0.0  17.940912  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
15  21.110258  0.0  21.110258  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
16  17.884781  0.0  17.884781  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
17  22.500977  0.0  22.500977  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
18  21.854013  0.0  21.854013  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
19  21.109085  0.0  21.109085  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
20  19.577404  0.0  19.577404  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
21  18.464193  0.0  18.464193  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
22  23.476776  0.0  23.476776  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
23  27.283598  0.0  27.283598  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
24  21.685919  0.0  21.685919  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
25  17.330853  0.0  17.330853  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
26  15.866392  0.0  15.866392  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
27  20.346628  0.0  20.346628  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
28  26.250093  0.0  26.250093  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   
29  24.492264  0.0  24.492264  0.0  0.0  0.0  9660.0  0.0  0.0  0.0  ...   

        p    q    r    s    t    u    v    w    x  label  
0    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
1    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
2    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
3    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
4    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
5    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
6    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
7    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
8    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
9    0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    2.0  
10  11.30  0.0  0.0  0.5  0.0  0.0  0.0  0.0  0.5    2.0  
11  11.35  0.0  0.0  0.6  0.0  0.0  0.0  0.0  0.6    2.0  
12  11.40  0.0  0.0  0.7  0.0  0.0  0.0  0.0  0.7    2.0  
13  11.45  0.0  0.0  0.8  0.0  0.0  0.0  0.0  0.8    2.0  
14  11.50  0.0  0.0  0.9  0.0  0.0  0.0  0.0  0.9    2.0  
15  11.55  0.0  0.0  0.5  0.0  0.0  0.0  0.0  0.5    2.0  
16  11.30  0.0  0.0  0.6  0.0  0.0  0.0  0.0  0.6    2.0  
17  11.35  0.0  0.0  0.7  0.0  0.0  0.0  0.0  0.7    2.0  
18  11.40  0.0  0.0  0.8  0.0  0.0  0.0  0.0  0.8    2.0  
19  11.45  0.0  0.0  0.9  0.0  0.0  0.0  0.0  0.9    2.0  
20  11.50  0.0  0.0  0.5  0.0  0.0  0.0  0.0  0.5    2.0  
21  11.55  0.0  0.0  0.6  0.0  0.0  0.0  0.0  0.6    2.0  
22  11.30  0.0  0.0  0.7  0.0  0.0  0.0  0.0  0.7    2.0  
23  11.35  0.0  0.0  0.8  0.0  0.0  0.0  0.0  0.8    2.0  
24  11.40  0.0  0.0  0.9  0.0  0.0  0.0  0.0  0.9    2.0  
25  11.45  0.0  0.0  0.5  0.0  0.0  0.0  0.0  0.5    2.0  
26  11.50  0.0  0.0  0.6  0.0  0.0  0.0  0.0  0.6    2.0  
27 

In [63]:
source_pd_data

a    b    c    d    e    f    g    h    i    j  ...    p    q    r  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3085  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3086  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3087  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3088  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3089  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        s    t    u    v    w    x  label  
0     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
1     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
2     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
3     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
4     0.0  0.0  0.0  0.0  0.0  0.0    2.0  
...   ...  ...  ...  ...  ...  ...    ...  
3085  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
3086  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
3087  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
3088  0.0  0.0  0.0  0.0  0.0  0.0    1.0  
3089  0.0  0.0  0.0  0.0  0.0  0.0    1.0  

[49790 rows x 25 columns]

In [75]:
dst_pd_data = pd.read_csv(dst_files[0].absolute(),encoding='gbk',dtype='float32')
dst_pd_data.columns = new_col
for file in tqdm(dst_files[1:]):
    d = pd.read_csv(file.absolute(),encoding='gbk')
    d.columns = new_col
    dst_pd_data = pd.concat([dst_pd_data,d])
    
print(source_pd_data.shape)
print(source_pd_data.isnull().sum())
dst_pd_data.to_csv("./dst_data.csv",index=False)
    

100%|██████████| 19/19 [00:00<00:00, 229.52it/s]


(49790, 25)
a        0
b        0
c        0
d        0
e        0
f        0
g        0
h        0
i        0
j        0
k        0
l        0
m        0
n        0
o        0
p        0
q        0
r        0
s        0
t        0
u        0
v        0
w        0
x        0
label    0
dtype: int64


In [85]:
d = pd.read_csv('./dst_data.csv')

#d.iloc[:,:-1]
#d.iloc[:,-1]
d.iloc[:,:-1].to_csv("./dst_data_feature.csv",index=False)
d.iloc[:,-1].to_csv("./dst_data_label.csv",index=False)



In [87]:
d = pd.read_csv('./source_data.csv')

d.iloc[:,:-1].to_csv("./source_data_feature.csv",index=False)
d.iloc[:,-1].to_csv("./source_data_label.csv",index=False)



In [92]:
d = pd.read_csv('./source_data_feature.csv')


(49790, 24)

In [102]:
import pandas as pd
from libtlda.flda import FeatureLevelDomainAdaptiveClassifier



X = pd.read_csv('./source_data_feature.csv').values
y = pd.read_csv('./source_data_label.csv').values
Z = pd.read_csv('./dst_data_feature.csv').values
k = pd.read_csv('./dst_data_label.csv').values



In [114]:
l,_ = Z.shape
l//2

17025

In [115]:
cls = FeatureLevelDomainAdaptiveClassifier()
cls.fit(X,y,Z[:l//2])


/home/yangxiao/projects/libTLDA/libtlda/flda.py:95: RuntimeWarning: invalid value encountered in true_divide
  iota = np.clip(1 - zeta / eta, 0, None)
/home/yangxiao/projects/libTLDA/libtlda/flda.py:136: RuntimeWarning: overflow encountered in exp
  alpha = np.exp(Xt) + np.exp(-Xt)
/home/yangxiao/projects/libTLDA/libtlda/flda.py:137: RuntimeWarning: overflow encountered in exp
  beta = np.exp(Xt) - np.exp(-Xt)
/home/yangxiao/projects/libTLDA/libtlda/flda.py:138: RuntimeWarning: overflow encountered in exp
  gamma = (np.exp(Xt).T * X.T).T + (np.exp(-Xt).T * X.T).T
/home/yangxiao/projects/libTLDA/libtlda/flda.py:138: RuntimeWarning: invalid value encountered in multiply
  gamma = (np.exp(Xt).T * X.T).T + (np.exp(-Xt).T * X.T).T
/home/yangxiao/projects/libTLDA/libtlda/flda.py:139: RuntimeWarning: overflow encountered in exp
  delta = (np.exp(Xt).T * X.T).T - (np.exp(-Xt).T * X.T).T
/home/yangxiao/projects/libTLDA/libtlda/flda.py:139: RuntimeWarning: invalid value encountered in multiply
 

         Current function value: nan
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1
         Current function value: nan
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1
         Current function value: nan
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1
         Current function value: nan
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1
         Current function value: nan
         Iterations: 0
         Function evaluations: 1
         Gradient evaluations: 1


In [147]:
res_check = k[l//2:]
a_len,_ = res_check.shape
l//2==a_len
# jk = res_check.reshape(a_len)
# jk

True

In [151]:
import numpy as np

res_predict=cls.predict(Z[l//2:])

res_check = k[l//2:]




[[ 0.  0.  0. ... -1. -1. -1.]
 [ 0.  0.  0. ... -1. -1. -1.]
 [ 0.  0.  0. ... -1. -1. -1.]
 ...
 [ 0.  0.  0. ... -1. -1. -1.]
 [ 0.  0.  0. ... -1. -1. -1.]
 [ 0.  0.  0. ... -1. -1. -1.]]



In [98]:
print(f'''
src shape:{src.shape}
src label:{src_label.shape}
dst shape:{dst.shape}

''')


src shape:(49790, 24)
src label:(49790, 1)
dst shape:(34050, 24)


